# Configuration for encoding pipeline

subjects:
  - 'p01'
  - 'p02'
  - 'p03'
  - 'p04'
  - 'p05'
  - 'p06'
  - 'p07'
  - 'p08'
  - 'p09'
  - 'p10'
  - 'p11'
  - 'p12'
  - 'p13'
  - 'p14'
  - 'p15'
  - 'p16'
  - 'p17'
  - 'p18'
  - 'p19'
  - 'p20'
  - 'p21'
  - 'p22'
  - 'p23'
  - 'p24'
  - 'p25'
  - 'p26'
  - 'p27'
  - 'p28'
  - 'p29'
  - 'p30'
  - 'p31'
  - 'p32'
  - 'p33'
  - 'p34'
  - 'p35'
  - 'p36'
  - 'p37'
  - 'p38'
  - 'p39'
  - 'p40'
  - 'p41'
  - 'p42'
  - 'p44'
  - 'p45'

# Directory paths
SSD_dir: '/Volumes/NeuroSSD/subCortex-speech/data'
results_cortex_dir: /Volumes/NeuroSSD/subCortex-speech/data/EEG/TRF/weights/cortex/
results_subcortex_dir: /Volumes/NeuroSSD/subCortex-speech/data/EEG/TRF/weights/cortex/subcortex
figures_dir: /Volumes/NeuroSSD/subCortex-speech/data/EEG/TRF/figures'

# Regularization parameter grid search
alphas:
  - 0.001
  - 0.01
  - 0.1
  - 1
  - 10
  - 100
  - 10000
  - 100000
  - 1000000
  - 10000000
  - 100000000
  - 1000000000

# Encoding parameters
subcortex:
  sfreq: 4096.0
  tmin: -0.01
  tmax: 0.03

cortex:
  sfreq: 128.0
  tmin: -0.3
  tmax: 0.6

# Plot results
make_plot: False